cloud:
  arvan:
    credentials:
      access_key: 033a8e2b-f000-4100-83e3-cab8dd47595c
      secret_key: 052af62e61c9347a188e034ef4f210c6b3294713
    region:
      static: default
    stack:
      uto: false

application:
  bucket:
    name: mycloudcomputing-course-bucket

spring:

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
#spring:
server:
  port: 9090